controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_homepage:
    path: /
    defaults:
        _controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
        template: /Home/index.html.twig
